// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY1Kj0aLGwsGfTi6ovPB570MouFN9DnuI',
    appId: '1:622292402778:web:0ba70f276fa1438a7dce63',
    messagingSenderId: '622292402778',
    projectId: 'sierra-pitching-academy',
    authDomain: 'sierra-pitching-academy.firebaseapp.com',
    storageBucket: 'sierra-pitching-academy.firebasestorage.app',
    measurementId: 'G-MY08FLHE3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIDPLDtcPJgd5r6PhgKe9LrUQPHOxl5_w',
    appId: '1:622292402778:android:2912446fc94f1dc07dce63',
    messagingSenderId: '622292402778',
    projectId: 'sierra-pitching-academy',
    storageBucket: 'sierra-pitching-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjcexGvh9olTeNrWuA-KIftGeBAvMlCK8',
    appId: '1:622292402778:ios:d7a66ee29743878f7dce63',
    messagingSenderId: '622292402778',
    projectId: 'sierra-pitching-academy',
    storageBucket: 'sierra-pitching-academy.firebasestorage.app',
    iosBundleId: 'com.teutondev.spaClientApp1',
  );

}